import toml


cfg = toml.load(open('config.toml', 'r', encoding='utf-8'))


WAIT_BETWEEN_ACCOUNTS = cfg.get('WAIT_BETWEEN_ACCOUNTS')
MAX_TRIES = cfg.get('MAX_TRIES')
RPC = cfg.get('RPC')
CAP_MONSTER_API_KEY = cfg.get('CAP_MONSTER_API_KEY')
TWO_CAPTCHA_API_KEY = cfg.get('TWO_CAPTCHA_API_KEY')
CAP_SOLVER_API_KEY = cfg.get('CAP_SOLVER_API_KEY')
THREADS_NUM = cfg.get('THREADS_NUM')
DISABLE_SSL = cfg.get('DISABLE_SSL')
UPDATE_STORAGE_ACCOUNT_INFO = cfg.get('UPDATE_STORAGE_ACCOUNT_INFO')
SKIP_FIRST_ACCOUNTS = cfg.get('SKIP_FIRST_ACCOUNTS')
RANDOM_ORDER = cfg.get('RANDOM_ORDER')
DO_ONCHAIN = cfg.get('DO_ONCHAIN')
WAIT_TX_TIME = cfg.get('WAIT_TX_TIME')
FAKE_TWITTER = cfg.get('FAKE_TWITTER')
DO_GALXE_TASKS = cfg.get('DO_GALXE_TASKS')
GALXE_CAMPAIGN_IDS = cfg.get('GALXE_CAMPAIGN_IDS')
HIDE_UNSUPPORTED = cfg.get('HIDE_UNSUPPORTED')
CHECKER_UPDATE_STORAGE = cfg.get('CHECKER_UPDATE_STORAGE')
